<!DOCTYPE html>
<html>

<head>
	<title>Error: try, catch, finally</title>
</head>

<body>
	<script>
		//1. try-catch 없이 에러 발생한 경우
		//('console'에 오타)
		//consol.log("log 메시지"); //Uncaught ReferenceError 에러(에러가 처리되지 않고 그대로 오류로 뜸)

		//console.log("log 정상 메시지");
		//해당 문장은 실행되지 않음(위에서 에러가 나면서 더 이상 아래를 진행하지 않기 때문)


		//2. try-catch로 에러를 처리해줄 경우
		try {
			//(에러: 'console'에 오타)
			consol.log("log 메시지")
			//catch: 브라우저에서 자동으로 생성하는 err 메시지를 받아서 블록 내 처리
		} catch (err) {
			console.log(err); //'Uncaught'란 말 없이 err 출력 (=> 에러처리 성공)
			//(err는 name과 message로 구성되어 있음)
			console.log(err.name);
			console.log(err.message);
		}

		//이 문장은 try/catch에서 에러 처리해줬으므로 정상 출력됨
		console.log("log 정상 메시지");


		//3. throw: 강제로 catch 블록으로 이동
		//	=> try 블록의 throw에 걸리면 아래줄로 더 이상 이동하지 않고 바로 catch문으로 넘어감
		var x = 5;

		try {
			if (x == "") throw "empty"; //x가 ""이면 강제로 catch의 err에 "empty" 던짐 (+ 아래줄 실행하지 않음)
			var y = x + 3;
			console.log(y);

		} catch (err) {
			console.log(`x is ${err}`); //(백틱으로 err 출력하기)

			//finally: try 코드가 에러가 나든 안 나든(catch문으로 넘어가든 안 넘어가든) 무조건 실행
		} finally {
			console.log("try/catch문 제일 마지막에 반드시 실행");
		}
	</script>
</body>

</html>